### ISSUE TITLE
Support alternative world export directories

### ISSUE THREAD

**Issue by MeItsLars** [sedgeland/haze#12]
**Observation**:
Currently, it is not possible to export worlds to directories other than the default Minecraft: Bedrock 'minecraftWorlds' directory.

**Problem**:
Applications like Minecraft: Education Edition and preview versions have different world directory paths, which is not supported.

**Suggested solution**:
Add a way to export to a different path. There are various ways in which this could be done, e.g.:
- `haze export cool-world [PATH]`

But I would additionally prefer some pre-defined templates, for example:
- `haze export cool-world` (for default Minecraft)
- `haze export cool-world education` (for Minecraft: Education Edition)
- `haze export cool-world preview` (for Minecraft: Preview)

**Comment by arexon** [comment]
A `--path` flag could also work. Examples:

- `haze export foo --path preview`
- `haze export bar --path D:\foo\bar\baz`

This flag in this case would accept built-in paths or arbitrary ones.
